# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_checkout:
      - git fetch --shallow-since=2023-01-01  || true

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

python:
  system_packages: false
  install:
    - method: pip
      path: .
      extra_requirements:
        - rtd

# Don't build any extra formats
formats: []
